Repository fkie-cad/fact_extractor, pull requests merged in 2019-08, with the labels that each got.

#24 Added Tektronix (extended) hex file format unpacker
  fact_extractor/plugins/unpacking/tektronix/__init__.py
  fact_extractor/plugins/unpacking/tektronix/code/__init__.py
  fact_extractor/plugins/unpacking/tektronix/code/tek.py
  fact_extractor/plugins/unpacking/tektronix/code/xtek.py
  fact_extractor/plugins/unpacking/tektronix/test/__init__.py
  fact_extractor/plugins/unpacking/tektronix/test/data/__init__.py
  fact_extractor/plugins/unpacking/tektronix/test/data/testfile.tek
  fact_extractor/plugins/unpacking/tektronix/test/data/testfile.xtek
  fact_extractor/plugins/unpacking/tektronix/test/test_plugin_tek.py
  fact_extractor/plugins/unpacking/tektronix/test/test_plugin_xtek.py
Labels: enhancement, under review

#27 fixed double usage of unsquashfs4-avm-le in unpacker
  fact_extractor/plugins/unpacking/squashFS/code/squash_fs.py
  fact_extractor/plugins/unpacking/squashFS/install.sh
  fact_extractor/plugins/unpacking/squashFS/test/test_plugin_squashfs.py
Labels: under review

#23 Raw encoded stream extraction
  fact_extractor/plugins/unpacking/ambarella/test/test_plugin_ambarella_romfs.py
  fact_extractor/plugins/unpacking/dji/test/test_plugin_dji_drones.py
  fact_extractor/plugins/unpacking/generic_carver/test/test_plugin_generic_carver_binwalk.py
  fact_extractor/plugins/unpacking/raw/code/raw.py
  fact_extractor/plugins/unpacking/raw/test/data/encoded.bin
  fact_extractor/plugins/unpacking/raw/test/data/nothing.bin
  fact_extractor/plugins/unpacking/raw/test/test_raw.py
  fact_extractor/version.py
Labels: enhancement, under review

#26 objcopy xtek file support, refactoring
  fact_extractor/plugins/unpacking/tektronix/code/tek.py
  fact_extractor/plugins/unpacking/tektronix/code/xtek.py
  fact_extractor/plugins/unpacking/tektronix/test/data/objcopy.xtek
  fact_extractor/plugins/unpacking/tektronix/test/test_plugin_xtek.py
Labels: enhancement, under review

#29 refactoring: pep8 -> flake8
  fact_extractor/install/common.py
  fact_extractor/plugins/unpacking/tektronix/code/tek.py
  fact_extractor/plugins/unpacking/tektronix/code/xtek.py
  fact_extractor/plugins/unpacking/tektronix/test/test_plugin_tek.py
  fact_extractor/plugins/unpacking/tektronix/test/test_plugin_xtek.py
  pytest.ini
Labels: enhancement, review requested

#33 Raw encoded stream extraction
  fact_extractor/plugins/unpacking/raw/code/raw.py
  fact_extractor/plugins/unpacking/raw/test/test_raw.py
Labels: refactoring, review requested
