Repository fkie-cad/fact_extractor, pull requests merged in 2020-06, with the labels that each got.

#56 jffs hotfix
  fact_extractor/helperFunctions/install.py
  fact_extractor/install/unpacker.py
  fact_extractor/plugins/unpacking/jffs2/install.sh
  fact_extractor/plugins/unpacking/srec/code/srec.py
Labels: HOTFIX, bug, review requested

#52 added v0.1 of the microtik extractor based on @botlabDev's work
  fact_extractor/plugins/unpacking/microtik/__init__.py
  fact_extractor/plugins/unpacking/microtik/code/__init__.py
  fact_extractor/plugins/unpacking/microtik/code/npk.py
  fact_extractor/plugins/unpacking/microtik/install.sh
  fact_extractor/plugins/unpacking/microtik/test/__init__.py
  fact_extractor/plugins/unpacking/microtik/test/test_npk.py
  fact_extractor/plugins/unpacking/yaffs/install.sh
Labels: enhancement, review requested

#54 D link shrs
  fact_extractor/plugins/unpacking/dlink_shrs/__init__.py
  fact_extractor/plugins/unpacking/dlink_shrs/code/__init__.py
  fact_extractor/plugins/unpacking/dlink_shrs/code/dlink_shrs.py
  fact_extractor/plugins/unpacking/dlink_shrs/internal/DecryptorLink.py
  fact_extractor/plugins/unpacking/dlink_shrs/test/__init__.py
  fact_extractor/plugins/unpacking/dlink_shrs/test/data/test.dec
  fact_extractor/plugins/unpacking/dlink_shrs/test/test_dlink_shrs.py
Labels: enhancement
